spring:
  application:
    name: eureka-server
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka
    register-with-eureka: true
    fetch-registry: true



